name: VENTY Pipeline Cron

on:
  schedule:
    - cron: '*/15 * * * *'   # alle 15 Minuten

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Python einrichten
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Abhängigkeiten installieren
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Pipeline ausführen
        run: |
          source venv/bin/activate
          python main.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
